INSERT INTO partners (name, address, city, postal_code, lat, lon, is_active) VALUES ('Laverie Le Havre', 'Adresse à préciser', 'Le Havre', '', 49.4974902, 0.1089192, true);
INSERT INTO partners (name, address, city, postal_code, lat, lon, is_active) VALUES ('Lavomatique', 'Adresse à préciser', 'Le Havre', '', 49.495438, 0.1230652, true);
INSERT INTO partners (name, address, city, postal_code, lat, lon, is_active) VALUES ('Laverie Le Havre', 'Adresse à préciser', 'Le Havre', '', 49.5002282, 0.1332127, true);
INSERT INTO partners (name, address, city, postal_code, lat, lon, is_active) VALUES ('Laverie d''Aplemont', '40 Avenue Paul Verlaine', 'Le Havre', '76610', 49.5091042, 0.1561362, true);
INSERT INTO partners (name, address, city, postal_code, lat, lon, is_active) VALUES ('Sec Eco', '72 Rue Joseph Morlent', 'Le Havre', '76600', 49.4970742, 0.0981359, true);
INSERT INTO partners (name, address, city, postal_code, lat, lon, is_active) VALUES ('L''Havrie Coty', '18 Rue d''Ingouville', 'Le Havre', '76600', 49.4973934, 0.1097815, true);
INSERT INTO partners (name, address, city, postal_code, lat, lon, is_active) VALUES ('H2 L''O', 'Adresse à préciser', 'Le Havre', '', 49.4867689, 0.1021088, true);
INSERT INTO partners (name, address, city, postal_code, lat, lon, is_active) VALUES ('Paris Pressing', '19 bis Place de l''Hôtel de Ville', 'Le Havre', '76600', 49.4922953, 0.1064983, true);
INSERT INTO partners (name, address, city, postal_code, lat, lon, is_active) VALUES ('Laverie Brindeau', '79 Rue Gustave Brindeau', 'Le Havre', '76600', 49.4932965, 0.1390016, true);
INSERT INTO partners (name, address, city, postal_code, lat, lon, is_active) VALUES ('Aqualogia', '102 Rue Paul Doumer', 'Le Havre', '76600', 49.4923177, 0.1059433, true);
INSERT INTO partners (name, address, city, postal_code, lat, lon, is_active) VALUES ('Pressing Gambetta', '88 Rue Voltaire', 'Le Havre', '76600', 49.4898152, 0.1060821, true);
INSERT INTO partners (name, address, city, postal_code, lat, lon, is_active) VALUES ('Laverie Le Havre', 'Adresse à préciser', 'Le Havre', '76620', 49.5049708, 0.1008337, true);
INSERT INTO partners (name, address, city, postal_code, lat, lon, is_active) VALUES ('Sec éco', 'Adresse à préciser', 'Le Havre', '', 49.4872738, 0.1069394, true);
INSERT INTO partners (name, address, city, postal_code, lat, lon, is_active) VALUES ('Laverie Le Havre', 'Adresse à préciser', 'Le Havre', '', 49.4859255, 0.1360007, true);
INSERT INTO partners (name, address, city, postal_code, lat, lon, is_active) VALUES ('Laverie Le Havre', 'Adresse à préciser', 'Le Havre', '', 49.485112, 0.1316198, true);
INSERT INTO partners (name, address, city, postal_code, lat, lon, is_active) VALUES ('Laverie Le Havre', 'Adresse à préciser', 'Le Havre', '', 49.5179595, 0.1000671, true);
INSERT INTO partners (name, address, city, postal_code, lat, lon, is_active) VALUES ('Laverie Le Havre', 'Adresse à préciser', 'Le Havre', '', 49.5178714, 0.1000129, true);
INSERT INTO partners (name, address, city, postal_code, lat, lon, is_active) VALUES ('Laverie Le Havre', 'Adresse à préciser', 'Le Havre', '', 49.51796, 0.1002482, true);
INSERT INTO partners (name, address, city, postal_code, lat, lon, is_active) VALUES ('Laverie Le Havre', 'Adresse à préciser', 'Le Havre', '', 49.5179841, 0.1001561, true);
INSERT INTO partners (name, address, city, postal_code, lat, lon, is_active) VALUES ('Laverie Le Havre', 'Adresse à préciser', 'Le Havre', '', 49.5179429, 0.1001308, true);
INSERT INTO partners (name, address, city, postal_code, lat, lon, is_active) VALUES ('Laverie Le Havre', 'Adresse à préciser', 'Le Havre', '', 49.5178308, 0.1001687, true);
INSERT INTO partners (name, address, city, postal_code, lat, lon, is_active) VALUES ('Propre & Sec', 'Adresse à préciser', 'Saint-Étienne', '', 45.4184587, 4.4189338, true);
INSERT INTO partners (name, address, city, postal_code, lat, lon, is_active) VALUES ('Pressing Fauriel', 'Adresse à préciser', 'Saint-Étienne', '', 45.4267053, 4.4030821, true);
INSERT INTO partners (name, address, city, postal_code, lat, lon, is_active) VALUES ('Hello', 'Adresse à préciser', 'Saint-Étienne', '', 45.4517105, 4.3826823, true);
INSERT INTO partners (name, address, city, postal_code, lat, lon, is_active) VALUES ('Laverie de Bergson', 'Adresse à préciser', 'Saint-Étienne', '', 45.4553334, 4.3833705, true);
INSERT INTO partners (name, address, city, postal_code, lat, lon, is_active) VALUES ('Hello', 'Adresse à préciser', 'Saint-Étienne', '', 45.4218198, 4.3919559, true);
INSERT INTO partners (name, address, city, postal_code, lat, lon, is_active) VALUES ('R''Pur', 'Adresse à préciser', 'Saint-Étienne', '', 45.436963, 4.3846294, true);
INSERT INTO partners (name, address, city, postal_code, lat, lon, is_active) VALUES ('Uni K Sec', 'Adresse à préciser', 'Saint-Étienne', '', 45.4499836, 4.3839877, true);
INSERT INTO partners (name, address, city, postal_code, lat, lon, is_active) VALUES ('Lys Pressing', 'Adresse à préciser', 'Saint-Étienne', '', 45.4414552, 4.3833968, true);
INSERT INTO partners (name, address, city, postal_code, lat, lon, is_active) VALUES ('City Laverie Plus', 'Adresse à préciser', 'Saint-Étienne', '', 45.439802, 4.4032979, true);
INSERT INTO partners (name, address, city, postal_code, lat, lon, is_active) VALUES ('Le Lavoir Marengo', 'Adresse à préciser', 'Saint-Étienne', '', 45.4438366, 4.3846931, true);
INSERT INTO partners (name, address, city, postal_code, lat, lon, is_active) VALUES ('Pressing des Arcades', 'Adresse à préciser', 'Saint-Étienne', '', 45.4402779, 4.3867529, true);
INSERT INTO partners (name, address, city, postal_code, lat, lon, is_active) VALUES ('GoGoWash', 'Adresse à préciser', 'Saint-Étienne', '', 45.4397569, 4.3856642, true);
INSERT INTO partners (name, address, city, postal_code, lat, lon, is_active) VALUES ('La Laverie', 'Adresse à préciser', 'Saint-Étienne', '', 45.4474761, 4.3872511, true);
INSERT INTO partners (name, address, city, postal_code, lat, lon, is_active) VALUES ('Citylaverie', 'Adresse à préciser', 'Saint-Étienne', '', 45.4408898, 4.3888901, true);
INSERT INTO partners (name, address, city, postal_code, lat, lon, is_active) VALUES ('Laverie Anatole France', 'Adresse à préciser', 'Saint-Étienne', '', 45.430757, 4.3894609, true);
INSERT INTO partners (name, address, city, postal_code, lat, lon, is_active) VALUES ('Les Frères Blanchisseurs', 'Adresse à préciser', 'Saint-Étienne', '', 45.4270735, 4.3904573, true);
INSERT INTO partners (name, address, city, postal_code, lat, lon, is_active) VALUES ('Laverie Saint-Roch', 'Adresse à préciser', 'Saint-Étienne', '', 45.4299783, 4.3935382, true);
INSERT INTO partners (name, address, city, postal_code, lat, lon, is_active) VALUES ('City Laverie', 'Rue Robespierre', 'Saint-Étienne', '', 45.4154591, 4.3946793, true);
INSERT INTO partners (name, address, city, postal_code, lat, lon, is_active) VALUES ('City Laverie', 'Adresse à préciser', 'Saint-Étienne', '', 45.4325984, 4.3802384, true);
INSERT INTO partners (name, address, city, postal_code, lat, lon, is_active) VALUES ('Lavallière Pressing', 'Adresse à préciser', 'Saint-Étienne', '', 45.4340171, 4.3926732, true);
INSERT INTO partners (name, address, city, postal_code, lat, lon, is_active) VALUES ('Les Frères Blanchisseurs', 'Adresse à préciser', 'Saint-Étienne', '', 45.4197025, 4.3925359, true);
INSERT INTO partners (name, address, city, postal_code, lat, lon, is_active) VALUES ('Wash Time', '22 Rue Michel Rondet', 'Saint-Étienne', '', 45.4380072, 4.384315, true);
INSERT INTO partners (name, address, city, postal_code, lat, lon, is_active) VALUES ('City Laverie', '13 Avenue de la Libération', 'Saint-Étienne', '', 45.437319, 4.3900742, true);
INSERT INTO partners (name, address, city, postal_code, lat, lon, is_active) VALUES ('Laverie Soleil', 'Adresse à préciser', 'Saint-Étienne', '', 45.4496914, 4.4029737, true);
INSERT INTO partners (name, address, city, postal_code, lat, lon, is_active) VALUES ('Green Laverie', 'Adresse à préciser', 'Saint-Étienne', '', 45.4391935, 4.3962168, true);
INSERT INTO partners (name, address, city, postal_code, lat, lon, is_active) VALUES ('GoGoWash', 'Adresse à préciser', 'Saint-Étienne', '', 45.4336173, 4.3925969, true);
INSERT INTO partners (name, address, city, postal_code, lat, lon, is_active) VALUES ('Laverie de Luxe', 'Adresse à préciser', 'Saint-Étienne', '', 45.4343517, 4.4375116, true);
INSERT INTO partners (name, address, city, postal_code, lat, lon, is_active) VALUES ('Pressing Bellevue', 'Adresse à préciser', 'Saint-Étienne', '', 45.4160615, 4.3932099, true);
INSERT INTO partners (name, address, city, postal_code, lat, lon, is_active) VALUES ('Laverie Saint-Étienne', 'Adresse à préciser', 'Saint-Étienne', '', 45.4347948, 4.417239, true);
INSERT INTO partners (name, address, city, postal_code, lat, lon, is_active) VALUES ('Les Frères Blanchisseurs', 'Adresse à préciser', 'Saint-Étienne', '', 45.4292411, 4.3940263, true);
INSERT INTO partners (name, address, city, postal_code, lat, lon, is_active) VALUES ('Laverie Saint-Étienne', 'Adresse à préciser', 'Saint-Étienne', '', 45.423376, 4.3976837, true);
INSERT INTO partners (name, address, city, postal_code, lat, lon, is_active) VALUES ('Laverie Saint-Étienne', 'Adresse à préciser', 'Saint-Étienne', '', 45.4118039, 4.4416416, true);
INSERT INTO partners (name, address, city, postal_code, lat, lon, is_active) VALUES ('Laverie Saint-Étienne', 'Adresse à préciser', 'Saint-Étienne', '', 45.4117579, 4.4416519, true);
INSERT INTO partners (name, address, city, postal_code, lat, lon, is_active) VALUES ('Laverie Saint-Étienne', 'Adresse à préciser', 'Saint-Étienne', '', 45.4117766, 4.4416032, true);
INSERT INTO partners (name, address, city, postal_code, lat, lon, is_active) VALUES ('Laverie Saint-Étienne', 'Adresse à préciser', 'Saint-Étienne', '', 45.411797, 4.4416956, true);
INSERT INTO partners (name, address, city, postal_code, lat, lon, is_active) VALUES ('Laverie Saint-Étienne', 'Adresse à préciser', 'Saint-Étienne', '', 45.4117971, 4.441689, true);
INSERT INTO partners (name, address, city, postal_code, lat, lon, is_active) VALUES ('Laverie Saint-Étienne', 'Adresse à préciser', 'Saint-Étienne', '', 45.411756, 4.4416404, true);
INSERT INTO partners (name, address, city, postal_code, lat, lon, is_active) VALUES ('Laverie Saint-Étienne', 'Adresse à préciser', 'Saint-Étienne', '', 45.43234, 4.4140057, true);
INSERT INTO partners (name, address, city, postal_code, lat, lon, is_active) VALUES ('Laverie Saint-Étienne', 'Adresse à préciser', 'Saint-Étienne', '', 45.4322799, 4.4140846, true);
INSERT INTO partners (name, address, city, postal_code, lat, lon, is_active) VALUES ('Laverie Saint-Étienne', 'Adresse à préciser', 'Saint-Étienne', '', 45.4322536, 4.4139658, true);
INSERT INTO partners (name, address, city, postal_code, lat, lon, is_active) VALUES ('Laverie Saint-Étienne', 'Adresse à préciser', 'Saint-Étienne', '', 45.432226, 4.4140012, true);
INSERT INTO partners (name, address, city, postal_code, lat, lon, is_active) VALUES ('Laverie Saint-Étienne', 'Adresse à préciser', 'Saint-Étienne', '', 45.4322868, 4.4139224, true);
INSERT INTO partners (name, address, city, postal_code, lat, lon, is_active) VALUES ('Laverie Saint-Étienne', 'Adresse à préciser', 'Saint-Étienne', '', 45.4423492, 4.4202551, true);
INSERT INTO partners (name, address, city, postal_code, lat, lon, is_active) VALUES ('Laverie Saint-Étienne', 'Adresse à préciser', 'Saint-Étienne', '', 45.4423925, 4.4203105, true);
INSERT INTO partners (name, address, city, postal_code, lat, lon, is_active) VALUES ('Laverie Saint-Étienne', 'Adresse à préciser', 'Saint-Étienne', '', 45.4424096, 4.4202821, true);
INSERT INTO partners (name, address, city, postal_code, lat, lon, is_active) VALUES ('Laverie Saint-Étienne', 'Adresse à préciser', 'Saint-Étienne', '', 45.4423658, 4.420226, true);
INSERT INTO partners (name, address, city, postal_code, lat, lon, is_active) VALUES ('Laverie Saint-Étienne', 'Adresse à préciser', 'Saint-Étienne', '', 45.4410226, 4.4215589, true);
INSERT INTO partners (name, address, city, postal_code, lat, lon, is_active) VALUES ('Laverie Saint-Étienne', 'Adresse à préciser', 'Saint-Étienne', '', 45.4410669, 4.4216092, true);
INSERT INTO partners (name, address, city, postal_code, lat, lon, is_active) VALUES ('Laverie Saint-Étienne', 'Adresse à préciser', 'Saint-Étienne', '', 45.4410833, 4.4214553, true);
INSERT INTO partners (name, address, city, postal_code, lat, lon, is_active) VALUES ('Laverie Saint-Étienne', 'Adresse à préciser', 'Saint-Étienne', '', 45.4411266, 4.4215076, true);